### ISSUE TITLE
Added parser to Neovim

### ISSUE THREAD

**Issue by ema2159** [Hubro/tree-sitter-robot#1]
Hello. I just created a [PR](https://github.com/nvim-treesitter/nvim-treesitter/pull/5111) in the [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) repo to add tree sitter highlighting support using your parser and highlights.

I would also like to know if your parser may be missing anything, or if there is any way to improve it. I would gladly try to lend you a hand.

**Comment by Hubro** [comment]
@ema2159 Great, thanks! :slightly_smiling_face: 

> I would also like to know if your parser may be missing anything, or if there is any way to improve it. I would gladly try to lend you a hand.

I'm terrible at finishing projects. This parser is still missing support for conditionals using the built-in `IF/ELSE` syntax:

http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#if-else-syntax

My plan was to implement this, then have it added to `nvim-treesitter`, but it's still somewhere on my TODO list :sweat_smile:

The parser works fine without this, since `IF` is just interpreted as a normal keyword, but it would be better if it could be highlighted differently.

**Comment by ema2159** [comment]
That is great! A good idea would be to have a README with a roadmap/wish list or something similar to list things that would be nice to add (i.e. queries for injections, indents, or folds). Then I can (or anyone else) contribute and add the features one by one. I will close the issue for now.

**Comment by Hubro** [comment]
@ema2159 Quick update in case you're curious. You gave me the nudge I needed to finish this project. Over the last few weeks I've:

- Added support for all of Robot Framework's native control structures (loops, conditionals, try/except)
- Added support for `RETURN`, `CONTINUE` and `BREAK` keywords
- Added support for inline Python expression syntax (`${{len([1, 2, 3])}}`)
- Fixed a bunch of bugs
- Added queries for folding and indents
- Updated `highlights.scm` for all the new features
- Opened PRs to update the parser in Neovim, Helix, as well as add the parser to the parser list in Tree-sitter's official docs

**Comment by ema2159** [comment]
Hey @Hubro. Amazing job! Your work will most certainly make my daily work and many others' easier. Thanks a lot.
